### ISSUE TITLE
More visibility for upgrade/Install VMware VM tools

### ISSUE THREAD

**Issue by richardtief** [sapcc/elektra#1054]
We would like to make the upgrade/installation of their VM tools more visible to the customer. 

The work on the VM tools doesn't seem to have had an impact yet - the number of uninstalled VM tools has increased by 5%, probably due to the additional deployment of VMs. 

<img width="669" alt="image (4)" src="https://user-images.githubusercontent.com/56597015/161007411-291b3c4c-3996-4c35-91fe-d2fbf5c9cca2.png">
<img width="666" alt="image (3)" src="https://user-images.githubusercontent.com/56597015/161007420-6b023caf-dfd2-4bf7-9254-e5822cd8615f.png">

We need some more visibility via the UI to improve the marketing of this VM tool update process. What can get the attention of customers? Maybe a action item on the home page? Or an additional warning triangle on the servers? 

What else can we do?

**Comment by edda** [comment]
We can't do the warning on the server in the list view because that would mean making [number of servers * 2] extra calls for that view. 

We can of course show a notification on the server list view that asks users to check each server individually. 

The best solution would be if you managed to add the information to the server's metadata. If that's not possible if you can fabricate a single query we could call on the server list view that gives us at least the number of servers with wrong VMTools for this project. Or even better if that single call would return the names and/or IDs of all affected servers in the project then we could also mark the individual servers in the list.

**Comment by richardtief** [comment]
Thanks @edda for your feedback. I am still looking for where we can add something to the server metadata. Could you please point me to the place where Elektra handles this so I can think about whether we can do that.

**Comment by hgw77** [comment]
closed because it is more than a year without activity
