### ISSUE TITLE
Restricted Flavor Resource Administration: keep bar with pages steady

### ISSUE THREAD

**Issue by BerndKue** [sapcc/elektra#1159]
![image](https://user-images.githubusercontent.com/12183628/205252011-b5dfea1c-e87d-48f3-85a0-d865341bc36b.png)
Especially in Domains with a lot of projects, like for instance Monsoon3, it is hard to click through all the pages to find projects with quota assigned.
When clicking through the bar in the bottom with "First", "Prev", "Next", "Last" and the page numbers is not steady. with every page change it is moving around. Sometimes that much, that I have to reposition the mouse. It would be much faster for a user if the bar would be on a steady place.

**Comment by ArtieReus** [comment]
Hi @BerndKue! Thank you for the feedback. If I understand you correctly the navigation bar moves a bit depending on the items are being shown in the list und it annoys you while navigating through the pages? If it is correct it works as designed... The navigation bar should stick at the bottom of the list since we don't know in advance how long it will be. In your case I would rather suggest sort the items by the column Quota to not have to paginate that much? Would that be ok? We would have first also to check if it possible to sort the items by column.

**Comment by BerndKue** [comment]
Yes, that's correct the navigation bar in the bottom moves depending on the list above. For instance, if the name of a project is longer than one line, the list gets longer and hence the bar is moving.
I thought it might be possible to have a fixed size of the list area and the bar below on the same spot all the time.

The second idea you brought up ist a very good one and actually the solution to what I want to achieve.
I actually wanted to find the projects with Quota assigned. If it is possible to sort the columns of the list, this would make it much easier for me.
Then I will not have to page through the list. But I guess nevertheless it would be nice to have a steady navigation bar in the bottom. ;)
