### ISSUE TITLE
Adjust FIP network assignment upon new project creation

### ISSUE THREAD

**Issue by rhalina** [sapcc/elektra#1199]
Rationale: 
We have a problem balancing the utilization of our FIP networks and migrating projects from one FIP network to another to rebalance, is a non-trivial issue. As such, we would like to ensure smart assignment of FIP networks to new projects. 

Upon creation of a new project in Elektra the wizard assigns a FIP network to the project. Right now it doesn't seem like there's any mechanism ensuring FIP networks are uniformly utlized. 

@hgw77 already implemented a sorting and selection mechanism for FIP networks upon new router creation (which satisfies a bunch of constrains on the networking side). The same mechanism should be used to select in which FIP network a new project will be placed.

**Comment by edda** [comment]
I'm not sure if this can be done by the same mechanism. On new project creation the currently agreed method is that the newest FIP network (i.e. the one with the highest number) is chosen. I remember that we had to hard code the network names because there are only specific networks that are allowed for assignment to projects and by convention those networks follow a specific naming scheme. So we might have to first check the logic there before we do hasty changes.
