### ISSUE TITLE
Unsupported Domain notification

### ISSUE THREAD

**Issue by vslijkerman** [sapcc/elektra#125]
I’m trying to figure out how to implement Elektra with OpenStack Ansible instead of DevStack. I keep getting an Unsupported Domain notification in the view.

Sidenote: Keystone v3 is active and I have an admin user with a Default domain and a RegionOne region in OpenStack.

Could you try and help me out getting this to work? Thanks in advance.

Screenshot:
![screenshot 2017-09-05 02 17 43](https://user-images.githubusercontent.com/4747193/30060963-c0d88b88-9245-11e7-967e-8eed1949cef0.png)

**Comment by edda** [comment]
We suspect that a recent addition might be the culprit here. We've removed the likely offender now. Could you pull the latest version from master and try again?

**Comment by vslijkerman** [comment]
I've pulled the latest version of master (SHA: ae90a431fbbe80f1bc2203a37579521a56424f55) and tried again. Still not working though. Any more ideas?

**Comment by vslijkerman** [comment]
Plus (possibly unrelated), I need to put `MONSOON_DASHBOARD_DEFAULT_DOMAIN=Default` in the .env file, otherwise, I keep getting invalid credentials. Why is this necessary?

**Comment by edda** [comment]
This is configurable because we didn't want to hardcode a default Openstack domain. In our case we couldn't use the `Default` domain because of technical restrictions in our landscape so we made it configurable what the default domain is. This value is used whenever you call the application's root url without specifying a domain as the first token after the slash. If you do specify an Openstack domain in the URL then that is used.

As to your problem. We suspect something isn't quite right with your configuration. Please double check your .env file, specifically the following values:

```
MONSOON_OPENSTACK_AUTH_API_ENDPOINT=https://your.keystone-endpoint.com/v3
MONSOON_OPENSTACK_AUTH_API_USERID=dashboard
MONSOON_OPENSTACK_AUTH_API_PASSWORD=DASHBOARD_USER_PASSWORD
MONSOON_OPENSTACK_AUTH_API_DOMAIN=Default
MONSOON_DASHBOARD_REGION=RegionOne
```

**Comment by vslijkerman** [comment]
That's kind of the configuration I have in place, except for testing purposes I have the password in there surrounded by quotation marks. Still doesn't seem to work. I will give it another try later on. Thanks for your input so far.

**Comment by edda** [comment]
You definitely don't need quotation marks for the password
