### ISSUE TITLE
[Elektra DNS] Zone requests mail not sent?

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#1265]
no mails are send to approvers of zone requests, I guess this is an issue of the send mail when one email address is not valid no mail is send. Need to check the approvers list,

**Comment by edda** [comment]
Needs some investigation what went wrong. First figure out where we can see the email logs.
Potentially we need to change how we send emails and rather than sending one email to multiple recipients, send multiple emails to single recipients instead.

**Comment by hgw77** [comment]
this problem was reported from Braun, Matthias and Vassil Dimitrov

**Comment by hgw77** [comment]
the dns admin are fetcht with the `list_ccadmin_master_dns_admins` function [here](https://github.com/sapcc/elektra/blob/master/plugins/dns_service/app/controllers/dns_service/request_zone_wizard_controller.rb#L27) and ist defined [here](https://github.com/sapcc/elektra/blob/master/plugins/dns_service/app/controllers/dns_service/request_zone_wizard_controller.rb#L77-L111)

these admins are saved to the request and if there is one email address not valid the whole send mail will stop to work for this request, for instance see [here](https://github.com/sapcc/elektra/blob/master/plugins/inquiry/app/mailers/inquiry/inquiry_mailer.rb#L66)

solution, send for every email address one email and not everything in one go?

**Comment by hgw77** [comment]
removed my solution to send each email because this was already done as error case in the model but I replaced the [SMTPFatalError](https://ruby-doc.org/stdlib-2.6.3/libdoc/net/smtp/rdoc/Net/SMTPFatalError.html) (this catches only [5XX Errors](https://en.wikipedia.org/wiki/List_of_SMTP_server_return_codes#%E2%80%94_5yz_Permanent_negative_completion)) with [SMTPError](https://ruby-doc.org/stdlib-2.6.3/libdoc/net/smtp/rdoc/Net/SMTPError.html) to catch more errors. It can be possible that we never catched the `email not send` error because this is not an FataError
