### ISSUE TITLE
Target audience not apparent from project page

### ISSUE THREAD

**Issue by namsral** [sapcc/elektra#128]
What is not apparent from the project page is wether Elektra is geared towards public or private clouds.

My initial thought was that Elektra was a drop-in replacement for Horizon, Horizon being geared towards public clouds with support for tenants and domains. Now having spent a little time setting-up Elektra with OpenStack Ansible it seems to me Elektra is geared towards private clouds. The default domain, API credentials requirements during setup, etc.

**Comment by edda** [comment]
I'm not quite sure I follow your reasoning. The configuration options you mention are in place so it is possible to run it against a variety of OpenStack installations. 

We currently use Elektra in our private cloud but we run it more like a public cloud (we have user self registration, users get full control over almost all aspects of their projects and can add new users and assign/revoke roles for users in their projects themselves). For some of these features we need the configured service user because they aren't possible in OpenStack for non-admin users.

While we currently run it only in our private cloud there is nothing major that comes to mind that we would have to change if we wanted to run it as a public cloud (except more documentation ;) and adding an authentication service to keystone that doesn't use our internal user store).

Admittedly there are pieces in there that are very specific to our scenario. It could definitely do with some work to make it more generally usable.

**Comment by namsral** [comment]
Thank you for the clarification.
