### ISSUE TITLE
[elektra] [EOV] VMware Images Not Displayed During Instance Creation Due to Incorrect Grouping

### ISSUE THREAD

**Issue by ArtieReus** [sapcc/elektra#1357]
When creating an instance, VMware images are not being displayed because they appear to be incorrectly grouped. We are currently filtering out all images with the 'image_type: "baremetal"' attribute when the user selects a VMware flavor. It appears that instead of grouping by 'image_type,' we need to group by 'hypervisor_type' to properly display VMware images.

Observed in the region `ap-cn-1` with the shared image `ksa2-tower-image`  when choosing the vmware flavor. But it is shown for baremetal flavors. 

Please see domain and project details in the thread:
https://convergedcloud.slack.com/archives/C2WPEPV8B/p1714975759206539

**Comment by sandzwerg** [comment]
When we started with baremetal our images had no `hypervisor_type` so we asked you to treat these images as baremetal images. By now all our BM images have a `hypervisor_type` so we as image team would be fine with treating these images without tag as VM images, or even as VM/BM images (because depending on the image they work for both).

**Comment by andypf** [comment]
Some years ago we decided to treat images without hypervisor_type as baremetal. 
From now on we will treat them as both "baremetal" and "vmware" because thus images run on both hypervisors.
