### ISSUE TITLE
[Feature](elektra): server hard reset shouldn't be tied to the web console

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#1423]
**Description**
The only way to hard reset a server from Elektra is via the top of the webconsole view. If the webconsole is slow to load or doesn't load then the button isn't shown because loading the console blocks the rest of the view from rendering. 

**Proposed Solution**
We should ideally do two things:
1. add hard reset action to normal server actions in server list view
2. load the console asynchronously so that the top part of the webconsole view with the buttons renders even if the console itself is slow

**Comment by hgw77** [comment]
The web console appeared as a blank white page due to an error in the service call responsible for retrieving the remote console URL. This issue has now been addressed. The error is now properly handled, and the web console page renders with an error message received from the API. This improvement ensures that users are informed of any issues rather than encountering an unresponsive blank page.

![Image](https://github.com/user-attachments/assets/f4555b12-3351-47ee-a9f9-cb1ae19ee6f3)
