### ISSUE TITLE
Remove VM's ports along with the VM deletion

### ISSUE THREAD

**Issue by kayrus** [sapcc/elektra#258]
When user deletes the VM, ports, which were used by this VM, are not deleted. In case the user creates/removes VMs multiple times, all these ports are remain in the system and it is hard to associate which port was used with which VM. Horizon dashboard removes ports as well, when the VM is removed.

**Comment by edda** [comment]
We need to differentiate here between different kinds of ports. Nova will delete all the ports it created when the instance was created but not the ports that the user created manually. This makes sense from my point of view because a user might want to reuse the manually created ones, we shouldn't assume that we can just delete them.

**Comment by kayrus** [comment]
@edda I have a hazy recollection that when I tried to remove a VM in non CC environment via API, ports were removed automatically. Most probably this odd bahvaior relates to non-standard Openstack network configuration.

**Comment by kayrus** [comment]
In addition, when user removes VM with the attached floatingip, floatingip is not released automatically, as well as the port. And this floatingip gets actual zombie status, but visible as `ACTIVE` for the Elektra UI and Openstack.

**Comment by andypf** [comment]
I think we've already resolved it.
