### ISSUE TITLE
FIP still attached when instances are removed

### ISSUE THREAD

**Issue by ArtieReus** [sapcc/elektra#287]
It is a bit confusing that FIP get not detached when an instance is removed. It is not clear that FIP has to be removed or the attached Port has to be released to be able to reuse the FIP to another instance.

**Comment by edda** [comment]
We had an issue here that we accidentally created ports manually for new instances. Manually created ports aren't cleaned up by Nova/Neutron when an instance is deleted. So that should be fixed now. There are cases where a port has be created manually it's 1) you choose a subnet or 2) you choose a fixed ip at instance creation. In those cases it's unfortunately "works as designed" that the port stays (with the attached fip)
