### ISSUE TITLE
Automatic quota increase for dns zone transfers doesn't work for subdomains

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#417]
A few months ago the pull request https://github.com/sapcc/elektra/pull/362 added a feature for zone transfer requests that would auto-increase the dns quota in the receiving project if quota was exhausted at the time of the zone transfer.

It turns out this doesn't work for subdomains. Those transfers get stuck in case of exhausted quota and the automatic quota increase doesn't happen. Please ensure this also works for subdomains.

**Comment by andypf** [comment]
The cause of the problem is the synchronization interval of the quotas, which is 30 minutes.

Limes is explicitly requested to increase the quota for the zones by one. This change is visible immediately. Next, this quota is immediately consumed again to create the zone. But this consumption will arrive in Elektra within the next 30 minutes. Elektra assumes that the quota for the zone is not yet used and therefore allows creation of additional zones without increasing the quota.

The Approver would have to wait a maximum of 30 minutes before he/she can accept further zone.

Solution: reduce the sync time as soon as a zone has been approved. Since the synchronization is very expensive, we want to avoid too frequent sync. Compromise is that we start a new sync after an approval, if the last one is older than 5 minutes. This means that the approver has to wait a maximum of 5 minutes before he can approve the next zone.
