### ISSUE TITLE
Masterdata responsible operator

### ISSUE THREAD

**Issue by Carthaca** [sapcc/elektra#430]
Hi,

the project wizard requires me to fill out the masterdata.
Some fields are required (like the cost object stuff), but the field "Operator" isn't.
Only later, when I save my masterdata and navigate to the project again I see the hint:
"The Masterdata was maintained but there are some data missing. 
Missing attributes: Responsible operator not specified"

It would make a better experience imho, when this field would be required directly in the form.
Else I have to maintain masterdata twice, because I'm naturally lazy and I only fill required fields on the first try.

What do you think?

BR,
Maurice

cc @chuan137

**Comment by hgw77** [comment]
this behavior was actually developed on purpose so that the user does not have to fill in everything the first time (often the user does not know all the data) and only needs to enter the most necessary data to continue to use the project. So it should be possible to come back at a later point in time to complete the data. This circumstance has led to the fact that the data often remained incomplete. Therefore, the behavior was adapted so that the mandatory fields now match the complete message of the api.
