### ISSUE TITLE
masterdata edit dialog gets stuck on invalid inheritance

### ISSUE THREAD

**Issue by majewsky** [sapcc/elektra#928]
I had a project that was set to inherit its cost object from the domain, but at the same time the domain did not allow inheritance.

This contradiction left the masterdata edit dialog wedged in an unresolvable state. The inheritance could not be disabled because the respective `<select>` is greyed out (on account of the domain forbidding inheritance), but since inheritance is technically enabled, one cannot enter a cost object.

**Comment by hgw77** [comment]
This is an edge case that should not happen, because it is not possible to disable the inheritance on domain level (in elektra) when projects enabled the inheritance from domain. But I guess the inheritance on domain level was disabled in the backend by force. Will take a look that the UI can handle that case.

**Comment by hgw77** [comment]
fixed
